name: xue_hua_file_operations
description: "Cross-platform Flutter plugin for picking files/directories, save-as, and opening files with the system default app."
version: 1.0.0
homepage: https://github.com/Matkurban/xue_hua_file_operations
repository: https://github.com/Matkurban/xue_hua_file_operations
topics:
  - files
  - file-picker
  - file-saver
  - document-picker
  - desktop


environment:
  sdk: ^3.12.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kurban.xue_hua_file_operations
        pluginClass: XueHuaFileOperationsPlugin
      ios:
        pluginClass: XueHuaFileOperationsPlugin
      linux:
        pluginClass: XueHuaFileOperationsPlugin
      macos:
        pluginClass: XueHuaFileOperationsPlugin
      windows:
        pluginClass: XueHuaFileOperationsPluginCApi
      web:
        pluginClass: XueHuaFileOperationsWeb
        fileName: xue_hua_file_operations_web.dart
